"""sode init — write factory.yaml + machine-local config + the active pointer.

Default ``--profile local --provider mock`` so a fresh clone runs offline (review
A12). Idempotent: an existing factory.yaml or local.yaml is preserved (never
clobbered) unless ``--force`` is given, so operator hand-edits survive re-init.
The active.json pointer is refreshed to the current sha on every run.
"""
from __future__ import annotations

import argparse

from ..config import loader, templates
from ..core import clock, paths
from ..core import subprocess as sp
from ..schema import registry, validate
from .dept_stubs import ensure_departments

_FACTORY_HEADER = (
    "# factory.yaml — the versioned factory definition (architecture section 3.3).\n"
    "# Generated by `sode init`; hand-editable (machine-local binding lives in .sode/local.yaml).\n"
)


def _git_head(root) -> str:
    res = sp.run(["git", "-C", str(root), "rev-parse", "HEAD"])
    return res.stdout.strip() if res.ok else "uncommitted"


def cmd_init(argv: "list[str]") -> int:
    parser = argparse.ArgumentParser(prog="sode init", add_help=True)
    parser.add_argument("--profile", choices=templates.PROFILES, default="local")
    parser.add_argument("--provider", choices=templates.PROVIDERS, default="mock")
    parser.add_argument("--force", action="store_true", help="overwrite factory.yaml / local.yaml")
    args = parser.parse_args(argv)

    root = paths.find_repo_root()
    actions: list[str] = []

    # factory.yaml — no-clobber unless --force.
    factory = templates.build_factory(args.profile, args.provider)
    errors = validate.validate(factory, registry.load_schema("factory"))
    if errors:
        print("sode init: internal error — generated factory.yaml is invalid:")
        for e in errors:
            print(f"  - {e}")
        return 1
    fpath = loader.factory_path(root)
    if fpath.exists() and not args.force:
        actions.append(f"kept existing {fpath.relative_to(root)} (use --force to overwrite)")
    else:
        loader.write_yaml_atomic(fpath, factory, header=_FACTORY_HEADER)
        actions.append(f"wrote {fpath.relative_to(root)} (profile={args.profile} provider={factory['stages']['implement']['provider']})")

    # .sode/local.yaml — machine-local; no-clobber unless --force (preserve bindings).
    local = templates.build_local(args.profile, args.provider)
    lpath = loader.local_path(root)
    if lpath.exists() and not args.force:
        actions.append("kept existing .sode/local.yaml")
    else:
        loader.write_yaml_atomic(lpath, local, header="# .sode/local.yaml — MACHINE-LOCAL (never committed).\n")
        actions.append("wrote .sode/local.yaml")

    # Seven department contract stubs — idempotent.
    made = ensure_departments(root)
    if made:
        actions.append(f"created department stubs: {', '.join(made)}")
    else:
        actions.append("departments present (7)")

    # .sode/active.json — refresh the pointer at the current sha.
    active = {
        "schema_version": 1,
        "sha": _git_head(root),
        "profile": args.profile,
        "provider": factory["stages"]["implement"]["provider"],
        "created_at": clock.now_iso(),
    }
    loader.write_json_atomic(loader.active_path(root), active)
    actions.append(f"wrote .sode/active.json (sha={active['sha'][:12]})")

    print("sode init:")
    for a in actions:
        print(f"  - {a}")
    return 0
